name: commandline
version: 0.0.1
author: "Dart Team <misc@dartlang.org>"
homepage: https://github.com/turnidge/commandline
description: >
 A library for building command line interfaces in Dart, supporting
 command line editing, history, tab completion, shortcuts, and hot keys.

dev_dependencies:
  test: ">=0.12.0 <0.13.0"
environment:
  sdk: '>=1.16.0 <2.0.0'
